sudo: required
dist: trusty
language: c

compiler: 
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev automake zip mingw-w64 git

script:
  -  git clone https://git.io/vPHe5 cpmn-opt && cd cpmn-opt
  - ./compileAll.sh
